-- Feature 025: order intents.
--
-- An intent is something a person is considering. It is not an order, and the difference is not a
-- matter of naming: there is no venue here, no order type, no time in force, no destination and no
-- expiry. Those absences are the safeguard — an intent carrying an order type would be one field
-- away from being transmissible, and the next feature to touch it would have to decide not to send
-- it. The migration test names each forbidden column, so a later addition argues with a failing
-- test rather than with this comment.
--
-- The product creates none of these. The vision describes a risk engine filtering recommendations a
-- strategy generated; feature 021 then measured that strategy over ten years and found it lost to
-- two of its three benchmarks. Generating trades from it, in a product that will not even say what
-- would close a limit gap, is the contradiction that would cost somebody money. Every row here was
-- written by the person whose portfolio it would change.
--
-- And nothing about the consequence is stored. What an intent would do is computed on every read
-- from the portfolio as it stands: the record is what somebody was thinking, and the consequence is
-- what acting today would do.

CREATE TABLE order_intents (
    id uuid PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES users(id),
    instrument_id uuid NOT NULL REFERENCES instruments(id),
    direction text NOT NULL CHECK (direction IN ('buy', 'sell')),
    quantity numeric(24,12) NOT NULL CHECK (quantity > 0),
    -- What the person expects to pay, per share, in the instrument's own listing currency. An
    -- expectation, not a fill: feature 022 owns what was actually paid.
    price numeric(24,12) NOT NULL CHECK (price > 0),
    costs numeric(24,12) NOT NULL DEFAULT 0 CHECK (costs >= 0),
    -- Three states, none of which implies transmission. 'acted_on' records that the person acted;
    -- it does not record a trade, because what they actually paid is a fact only they can assert.
    status text NOT NULL DEFAULT 'considering'
        CHECK (status IN ('considering', 'withdrawn', 'acted_on')),
    recorded_at timestamptz NOT NULL DEFAULT now(),
    settled_at timestamptz,
    -- Settled with a date, or under consideration without one. A withdrawn intent with no date is a
    -- state nobody can read.
    CHECK ((status = 'considering') = (settled_at IS NULL))
);

CREATE INDEX order_intents_owner_idx ON order_intents (user_id, recorded_at DESC);

COMMENT ON TABLE order_intents IS
    'What a person is considering. Never an order, never generated by the product, and never carrying anything a broker could act on.';
